version: '2.1'

services:

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: lab3-registry
#    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: lab3-config
#    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: lab3-gateway
#    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rest-api:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    image: lab3-rest-api
#    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"



  postgres:
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    image: lab3-postgres
#    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:


