server:
  port: 8081


spring:
  jpa:
    database-platform=org: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform : postgres
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}
    username: postgres
    password: ${POSTGRES_PASSWORD}


